# ===== Configuración de base de datos (POSTGRESQL - SUPABASE) =====
# IMPORTANTE: Para PostgreSQL usamos jdbc:postgresql://
spring.datasource.url=jdbc:postgresql://db.ufpxqmyqgydfcxurmszu.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Chikorita1!$
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Hibernate creará las tablas automáticamente

spring.jpa.show-sql=true

# ===== Configuración de puerto de la APP =====
# Koyeb buscará tu app en el puerto 8080
server.port=8080

# ===== Configuración de archivos =====
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
app.upload.dir=uploads
spring.web.resources.static-locations=file:uploads/