# 1. Conexión a Base de Datos (Render inyecta estos valores)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configuración de Hibernate
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update

# 3. Puerto del Servidor
server.port=${PORT:8080}

spring.servlet.multipart.enabled=true

# 4. Límites de carga (Para que acepten videos de hasta 50MB)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# 5. Configuración de Cloudinary (Usando variables de entorno)
# Esto evitará el error "Could not resolve placeholder" que apaga tu app
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

# 6. Optimización de conexiones
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=2