spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=false
# IMPORTANTE: 'update' para que no se borre tu base de datos cada vez
spring.jpa.hibernate.ddl-auto=update

server.port=${PORT:8080}

# Límites aumentados para videos
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=2

# Credenciales de Cloudinary (Asegúrate de que el secret sea idéntico al de tu consola)
cloudinary.cloud_name=dqt6imfq7
cloudinary.api_key=691414411868699
cloudinary.api_secret=pwOdoyekVbV0uaQ24jU7N8bvnGk